/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLlmRouteImport } from './routes/api/llm'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmRoute = ApiLlmRouteImport.update({
  id: '/api/llm',
  path: '/api/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-image' | '/api/llm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-image' | '/api/llm'
  id: '__root__' | '/' | '/api/generate-image' | '/api/llm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiLlmRoute: typeof ApiLlmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm': {
      id: '/api/llm'
      path: '/api/llm'
      fullPath: '/api/llm'
      preLoaderRoute: typeof ApiLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiLlmRoute: ApiLlmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
