/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as DesignProfilesRouteImport } from './routes/design-profiles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as View_allRouteImport } from './routes/view_all'
import { Route as ApiLlmRouteImport } from './routes/api/llm'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignProfilesRoute = DesignProfilesRouteImport.update({
  id: '/design-profiles',
  path: '/design-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const View_allRoute = View_allRouteImport.update({
  id: '/view_all',
  path: '/view_all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmRoute = ApiLlmRouteImport.update({
  id: '/api/llm',
  path: '/api/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/view_all': typeof View_allRoute
  '/design-profiles': typeof DesignProfilesRoute
  '/prompts': typeof PromptsRoute
  '/styles': typeof StylesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/view_all': typeof View_allRoute
  '/design-profiles': typeof DesignProfilesRoute
  '/prompts': typeof PromptsRoute
  '/styles': typeof StylesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/view_all': typeof View_allRoute
  '/design-profiles': typeof DesignProfilesRoute
  '/prompts': typeof PromptsRoute
  '/styles': typeof StylesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/view_all'
    | '/design-profiles'
    | '/prompts'
    | '/styles'
    | '/workspace'
    | '/api/generate-image'
    | '/api/llm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/view_all'
    | '/design-profiles'
    | '/prompts'
    | '/styles'
    | '/workspace'
    | '/api/generate-image'
    | '/api/llm'
  id:
    | '__root__'
    | '/'
    | '/view_all'
    | '/design-profiles'
    | '/prompts'
    | '/styles'
    | '/workspace'
    | '/api/generate-image'
    | '/api/llm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  View_allRoute: typeof View_allRoute
  DesignProfilesRoute: typeof DesignProfilesRoute
  PromptsRoute: typeof PromptsRoute
  StylesRoute: typeof StylesRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiLlmRoute: typeof ApiLlmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-profiles': {
      id: '/design-profiles'
      path: '/design-profiles'
      fullPath: '/design-profiles'
      preLoaderRoute: typeof DesignProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view_all': {
      id: '/view_all'
      path: '/view_all'
      fullPath: '/view_all'
      preLoaderRoute: typeof View_allRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm': {
      id: '/api/llm'
      path: '/api/llm'
      fullPath: '/api/llm'
      preLoaderRoute: typeof ApiLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  View_allRoute: View_allRoute,
  DesignProfilesRoute: DesignProfilesRoute,
  PromptsRoute: PromptsRoute,
  StylesRoute: StylesRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiLlmRoute: ApiLlmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
